; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "KinderSort"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "KinderSort"
#define MyAppExeName "KinderSort.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{9A73A16A-23F8-4A1C-9E49-DDFDE8C16259}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\{#MyAppName}
DisableProgramGroupPage=yes
; PrivilegesRequired=lowest means it installs without requiring admin rights, perfect for standard user environments
PrivilegesRequired=lowest
OutputDir=c:\Users\ngjun\KinderSort\Output
OutputBaseFilename=KinderSort_Setup
Compression=lzma2
SolidCompression=yes
WizardStyle=modern

#if FileExists("c:\Users\ngjun\KinderSort\app_icon.ico")
SetupIconFile=c:\Users\ngjun\KinderSort\app_icon.ico
#endif

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "c:\Users\ngjun\KinderSort\dist\KinderSort\KinderSort.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "c:\Users\ngjun\KinderSort\dist\KinderSort\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
#if FileExists("c:\Users\ngjun\KinderSort\app_icon.ico")
Name: "{userprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\_internal\app_icon.ico"
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\_internal\app_icon.ico"
#else
Name: "{userprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
#endif

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
